
const Ingredients = [
    {
        id: 1,
        name: 'Strawberry',
        calories: 32, 
        protein: 0.7, 
        carbs: 7.7, 
        sugar: 4.9, 
        fiber: 2, 
        fat: 0.3,
        tastiness: 3,
        pain: 0,
        bitter: 0,
    },
    {
        id: 2,
        name: 'Pear',
        calories: 58, 
        protein: 0.38, 
        carbs: 15.46, 
        sugar: 9.8, 
        fiber: 3.1, 
        fat: 0.1,
        tastiness: 2,
        pain: 0,
        bitter: 0,
    },
    {
        id: 3,
        name: 'Apple',
        calories: 51, 
        protein: 0.6, 
        carbs: 11.6, 
        sugar: 11.6, 
        fiber: 1.3, 
        fat: 0.5,
        tastiness: 1,
        pain: 0,
        bitter: 0,
    },
    {
        id: 4,
        name: 'Watermelon',
        calories: 30.9, 
        protein: 0.55, 
        carbs: 6.5, 
        sugar: 6.2, 
        fiber: 0.29, 
        fat: 0.24,
        tastiness: 3,
        pain: 0,
        bitter: 0,
    },
    {
        id: 5,
        name: 'Banana(peeled)',
        calories: 87.5, 
        protein: 1.2, 
        carbs: 18.3, 
        sugar: 13.5, 
        fiber: 1.8, 
        fat: 0.4,
        tastiness: 1,
        pain: 0,
        bitter: 0,
    },
    {
        id: 6,
        name: 'Chili', //TTShneheiuranrebied
        calories: 9, 
        protein: 0.4, 
        carbs: 1.8, 
        sugar: 0.0, 
        fiber: 0.0, 
        fat: 0.0,
        tastiness: 1,
        pain: 2,
        bitter: 0,
    },
    {
        id: 7,
        name: 'Pineapple',
        calories: 63, 
        protein: 0.4, 
        carbs: 14.0, 
        sugar: 12.0, 
        fiber: 0.6, 
        fat: 0.0,
        tastiness: 2,
        pain: 1,
        bitter: 1,
    },
    {
        id: 8,
        name: 'Lemon(peeled)',
        calories: 32.9, 
        protein: 0.6, 
        carbs: 2.2, 
        sugar: 2.2, 
        fiber: 2.8, 
        fat: 0.2,
        tastiness: 1,
        pain: 1,
        bitter: 2,
    },
    {
        id: 9,
        name: 'Orange(peeled)',
        calories: 45.7, 
        protein: 0.6, 
        carbs: 8.9, 
        sugar: 8.9, 
        fiber: 2.1, 
        fat: 0.1,
        tastiness: 2,
        pain: 0,
        bitter: 0,
    },
    {
        id: 10,
        name: 'Lime(unpeeled)', 
        calories: 30.0, 
        protein: 0.7, 
        carbs: 10.5, 
        sugar: 1.7, 
        fiber: 0.0, 
        fat: 0.2,
        tastiness: 1,
        pain: 2,
        bitter: 3,
    },
    { 
        id: 11,
        name: 'Lime(peeled)',
        calories: 9, 
        protein: 0.7, 
        carbs: 0.8, 
        sugar: 0.8, 
        fiber: 0.0, 
        fat: 0.3,
        tastiness: 1,
        pain: 1,
        bitter: 2,
    }
];

export default Ingredients;
